import React from 'react';
import { 
  LayoutDashboard, 
  DollarSign, 
  Users, 
  Package, 
  ShoppingCart, 
  BarChart3, 
  Settings, 
  Bell, 
  Search,
  Menu,
  X,
  TrendingUp,
  TrendingDown,
  Briefcase,
  AlertCircle,
  Sparkles,
  Mail,
  Calendar,
  Download,
  Plus,
  Activity,
  Server,
  CheckCircle,
  Clock,
  ArrowRight,
  FileText,
  Truck,
  CreditCard,
  UserPlus,
  MapPin,
  ClipboardList,
  Container,
  Edit2,
  Trash2,
  LayoutGrid,
  List,
  Columns,
  UserCheck,
  UserX,
  Shield,
  Filter,
  Sun,
  Moon,
  Factory,
  Building,
  Landmark,
  ScrollText,
  PieChart,
  ChevronDown,
  ChevronRight,
  Wrench,
  Hammer,
  Ship,
  Calculator,
  Percent,
  Target,
  Award,
  HardHat,
  Box,
  Globe,
  Zap,
  Layers,
  ShoppingBag
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Finance: DollarSign,
  HR: Users,
  Inventory: Package,
  Sales: ShoppingCart,
  CRM: Briefcase,
  Analytics: BarChart3,
  Settings: Settings,
  Notification: Bell,
  Search: Search,
  Menu: Menu,
  Close: X,
  Up: TrendingUp,
  Down: TrendingDown,
  Alert: AlertCircle,
  AI: Sparkles,
  Email: Mail,
  Calendar: Calendar,
  Download: Download,
  Plus: Plus,
  Activity: Activity,
  Server: Server,
  Check: CheckCircle,
  Clock: Clock,
  ArrowRight: ArrowRight,
  File: FileText,
  Truck: Truck,
  CreditCard: CreditCard,
  UserPlus: UserPlus,
  MapPin: MapPin,
  Clipboard: ClipboardList,
  Container: Container,
  Edit: Edit2,
  Delete: Trash2,
  Grid: LayoutGrid,
  List: List,
  Kanban: Columns,
  UserCheck: UserCheck,
  UserX: UserX,
  Shield: Shield,
  Filter: Filter,
  Sun: Sun,
  Moon: Moon,
  Factory: Factory,
  Building: Building,
  Bank: Landmark,
  LC: ScrollText,
  PieChart: PieChart,
  ChevronDown: ChevronDown,
  ChevronRight: ChevronRight,
  Wrench: Wrench,
  Production: Hammer,
  Ship: Ship,
  Calculator: Calculator,
  Tax: Percent,
  Target: Target,
  Award: Award,
  Safety: HardHat,
  Box: Box,
  Network: Globe,
  Project: Zap,
  Layers: Layers,
  Bag: ShoppingBag
};
