-- SpringERP Database Schema Migration
-- This script creates the initial database schema for all ERP modules

-- Tenants Table
CREATE TABLE IF NOT EXISTS tenants (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_name VARCHAR(255) NOT NULL UNIQUE,
    tenant_identifier VARCHAR(100) NOT NULL UNIQUE,
    description TEXT,
    admin_email VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    subscription_tier VARCHAR(50),
    max_users INT DEFAULT 10,
    max_storage_gb INT DEFAULT 100,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    trial_end_date TIMESTAMP NULL,
    contract_end_date TIMESTAMP NULL,
    INDEX idx_tenant_identifier (tenant_identifier),
    INDEX idx_is_active (is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Audit Logs Table
CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    user_id BIGINT,
    user_name VARCHAR(255),
    ip_address VARCHAR(45),
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    old_values LONGTEXT,
    new_values LONGTEXT,
    change_description VARCHAR(1000),
    tenant_id BIGINT,
    request_id VARCHAR(100),
    INDEX idx_entity_id (entity_id),
    INDEX idx_entity_type (entity_type),
    INDEX idx_user_id (user_id),
    INDEX idx_timestamp (timestamp),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Chart of Accounts Table
CREATE TABLE IF NOT EXISTS chart_of_accounts (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    account_code VARCHAR(50) NOT NULL UNIQUE,
    account_name VARCHAR(255) NOT NULL,
    account_type VARCHAR(50) NOT NULL,
    account_category VARCHAR(100),
    description TEXT,
    normal_balance VARCHAR(20),
    current_balance DECIMAL(19,2) DEFAULT 0.00,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    parent_account_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_account_code (account_code),
    INDEX idx_account_type (account_type),
    INDEX idx_parent_account (parent_account_id),
    INDEX idx_tenant_id (tenant_id),
    FOREIGN KEY (parent_account_id) REFERENCES chart_of_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Journal Entries Table
CREATE TABLE IF NOT EXISTS journal_entries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    entry_number VARCHAR(50) NOT NULL UNIQUE,
    journal_date DATE NOT NULL,
    posting_date DATE,
    reference_number VARCHAR(100),
    description VARCHAR(500) NOT NULL,
    total_debit DECIMAL(19,2) DEFAULT 0.00,
    total_credit DECIMAL(19,2) DEFAULT 0.00,
    status VARCHAR(50) NOT NULL DEFAULT 'DRAFT',
    approval_status VARCHAR(50) DEFAULT 'PENDING',
    approver_id BIGINT,
    approval_notes TEXT,
    memo TEXT,
    is_balanced BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_journal_date (journal_date),
    INDEX idx_entry_number (entry_number),
    INDEX idx_status (status),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- General Ledger Table
CREATE TABLE IF NOT EXISTS general_ledger (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    account_id BIGINT NOT NULL,
    journal_entry_id BIGINT NOT NULL,
    reference_number VARCHAR(100),
    description VARCHAR(500),
    debit_amount DECIMAL(19,2) DEFAULT 0.00,
    credit_amount DECIMAL(19,2) DEFAULT 0.00,
    transaction_date DATE NOT NULL,
    posting_date DATE NOT NULL,
    entry_type VARCHAR(50),
    status VARCHAR(50) DEFAULT 'DRAFT',
    memo TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_account_id (account_id),
    INDEX idx_transaction_date (transaction_date),
    INDEX idx_journal_entry_id (journal_entry_id),
    INDEX idx_posting_date (posting_date),
    INDEX idx_tenant_id (tenant_id),
    FOREIGN KEY (account_id) REFERENCES chart_of_accounts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Departments Table
CREATE TABLE IF NOT EXISTS departments (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    department_code VARCHAR(50) NOT NULL UNIQUE,
    department_name VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    manager_id BIGINT,
    budget DECIMAL(19,2),
    cost_center_code VARCHAR(100),
    parent_department_id BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_department_code (department_code),
    INDEX idx_parent_department_id (parent_department_id),
    INDEX idx_tenant_id (tenant_id),
    FOREIGN KEY (parent_department_id) REFERENCES departments(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Employees Table
CREATE TABLE IF NOT EXISTS employees (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id VARCHAR(50) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(20),
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(20),
    national_id VARCHAR(50),
    passport_number VARCHAR(100),
    department_id BIGINT NOT NULL,
    designation VARCHAR(255),
    employment_type VARCHAR(50),
    employment_status VARCHAR(50) DEFAULT 'ACTIVE',
    date_of_joining DATE NOT NULL,
    date_of_termination DATE,
    base_salary DECIMAL(19,2),
    salary_currency VARCHAR(3) DEFAULT 'USD',
    salary_frequency VARCHAR(50) DEFAULT 'MONTHLY',
    reporting_manager_id BIGINT,
    office_location VARCHAR(255),
    employee_photo_url VARCHAR(500),
    address VARCHAR(500),
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    emergency_contact_name VARCHAR(255),
    emergency_contact_phone VARCHAR(20),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_employee_id (employee_id),
    INDEX idx_user_id (user_id),
    INDEX idx_department_id (department_id),
    INDEX idx_email (email),
    INDEX idx_tenant_id (tenant_id),
    FOREIGN KEY (department_id) REFERENCES departments(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Attendance Table
CREATE TABLE IF NOT EXISTS attendances (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    check_in_time TIME,
    check_out_time TIME,
    attendance_status VARCHAR(50) NOT NULL,
    working_hours DECIMAL(5,2),
    overtime_hours DECIMAL(5,2) DEFAULT 0.00,
    remarks TEXT,
    approved_by BIGINT,
    is_approved BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_employee_id (employee_id),
    INDEX idx_attendance_date (attendance_date),
    INDEX idx_tenant_id (tenant_id),
    UNIQUE KEY unique_emp_date (employee_id, attendance_date),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Leaves Table
CREATE TABLE IF NOT EXISTS leaves (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    leave_type VARCHAR(50) NOT NULL,
    leave_start_date DATE NOT NULL,
    leave_end_date DATE NOT NULL,
    number_of_days INT NOT NULL,
    half_day BOOLEAN NOT NULL DEFAULT FALSE,
    half_day_type VARCHAR(50),
    reason LONGTEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    approved_by BIGINT,
    approval_date DATE,
    approval_comments TEXT,
    is_paid BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_employee_id (employee_id),
    INDEX idx_leave_start_date (leave_start_date),
    INDEX idx_status (status),
    INDEX idx_tenant_id (tenant_id),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Salaries Table
CREATE TABLE IF NOT EXISTS salaries (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    salary_month DATE NOT NULL,
    basic_salary DECIMAL(19,2) NOT NULL,
    gross_salary DECIMAL(19,2),
    net_salary DECIMAL(19,2),
    total_allowances DECIMAL(19,2) DEFAULT 0.00,
    total_deductions DECIMAL(19,2) DEFAULT 0.00,
    hra DECIMAL(19,2),
    dearness_allowance DECIMAL(19,2),
    conveyance DECIMAL(19,2),
    medical_allowance DECIMAL(19,2),
    other_allowances DECIMAL(19,2) DEFAULT 0.00,
    income_tax DECIMAL(19,2) DEFAULT 0.00,
    provident_fund DECIMAL(19,2) DEFAULT 0.00,
    insurance DECIMAL(19,2) DEFAULT 0.00,
    loan_deduction DECIMAL(19,2) DEFAULT 0.00,
    other_deductions DECIMAL(19,2) DEFAULT 0.00,
    working_days INT,
    actual_days_worked INT,
    payment_status VARCHAR(50) DEFAULT 'PENDING',
    payment_date DATE,
    payment_method VARCHAR(50),
    remarks TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_employee_id (employee_id),
    INDEX idx_salary_month (salary_month),
    INDEX idx_payment_status (payment_status),
    INDEX idx_tenant_id (tenant_id),
    UNIQUE KEY unique_emp_month (employee_id, salary_month),
    FOREIGN KEY (employee_id) REFERENCES employees(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Warehouses Table
CREATE TABLE IF NOT EXISTS warehouses (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    warehouse_name VARCHAR(255) NOT NULL UNIQUE,
    warehouse_code VARCHAR(50) NOT NULL UNIQUE,
    address VARCHAR(500) NOT NULL,
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    phone VARCHAR(20),
    email VARCHAR(255),
    manager_id BIGINT,
    total_capacity INT,
    current_utilization INT DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    warehouse_type VARCHAR(50),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_warehouse_code (warehouse_code),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Inventory Items Table
CREATE TABLE IF NOT EXISTS inventory_items (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    sku VARCHAR(100) NOT NULL UNIQUE,
    product_id BIGINT NOT NULL,
    warehouse_id BIGINT,
    quantity_on_hand INT NOT NULL DEFAULT 0,
    quantity_reserved INT DEFAULT 0,
    quantity_available INT NOT NULL DEFAULT 0,
    reorder_level INT NOT NULL DEFAULT 10,
    reorder_quantity INT,
    unit_cost DECIMAL(19,2),
    last_counted_at TIMESTAMP,
    last_movement_date TIMESTAMP,
    location VARCHAR(255),
    batch_number VARCHAR(100),
    expiry_date TIMESTAMP,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_product_id (product_id),
    INDEX idx_warehouse_id (warehouse_id),
    INDEX idx_sku (sku),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Stock Movements Table
CREATE TABLE IF NOT EXISTS stock_movements (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    inventory_item_id BIGINT NOT NULL,
    movement_type VARCHAR(50) NOT NULL,
    quantity_moved INT NOT NULL,
    unit_price DECIMAL(19,2),
    total_value DECIMAL(19,2),
    movement_date DATE NOT NULL,
    reference_document VARCHAR(100),
    reference_id BIGINT,
    from_location VARCHAR(255),
    to_location VARCHAR(255),
    reason VARCHAR(500),
    notes LONGTEXT,
    approved_by BIGINT,
    approval_date DATE,
    status VARCHAR(50) DEFAULT 'PENDING',
    batch_number VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_inventory_item_id (inventory_item_id),
    INDEX idx_movement_date (movement_date),
    INDEX idx_movement_type (movement_type),
    INDEX idx_tenant_id (tenant_id),
    FOREIGN KEY (inventory_item_id) REFERENCES inventory_items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Assets Table
CREATE TABLE IF NOT EXISTS assets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    asset_code VARCHAR(100) NOT NULL UNIQUE,
    asset_name VARCHAR(255) NOT NULL,
    asset_type VARCHAR(50) NOT NULL,
    category VARCHAR(100),
    description LONGTEXT,
    acquisition_date DATE NOT NULL,
    acquisition_cost DECIMAL(19,2) NOT NULL,
    salvage_value DECIMAL(19,2) DEFAULT 0.00,
    useful_life_years INT,
    depreciation_method VARCHAR(50),
    accumulated_depreciation DECIMAL(19,2) DEFAULT 0.00,
    book_value DECIMAL(19,2),
    currency VARCHAR(3) DEFAULT 'USD',
    location VARCHAR(255),
    responsible_person_id BIGINT,
    asset_status VARCHAR(50) DEFAULT 'IN_SERVICE',
    disposal_date DATE,
    disposal_value DECIMAL(19,2),
    disposal_method VARCHAR(255),
    serial_number VARCHAR(100),
    model_number VARCHAR(100),
    manufacturer VARCHAR(255),
    warranty_expiry_date DATE,
    image_url VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_asset_code (asset_code),
    INDEX idx_asset_type (asset_type),
    INDEX idx_acquisition_date (acquisition_date),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Notifications Table
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    recipient_email VARCHAR(255),
    notification_type VARCHAR(50) NOT NULL,
    channel VARCHAR(50) NOT NULL,
    subject VARCHAR(500),
    message LONGTEXT,
    status VARCHAR(50) DEFAULT 'PENDING',
    sent_at TIMESTAMP,
    read_at TIMESTAMP,
    retry_count INT DEFAULT 0,
    error_message TEXT,
    related_entity_type VARCHAR(100),
    related_entity_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_recipient_id (recipient_id),
    INDEX idx_created_at (created_at),
    INDEX idx_status (status),
    INDEX idx_notification_type (notification_type),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Workflow Definitions Table
CREATE TABLE IF NOT EXISTS workflow_definitions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    workflow_name VARCHAR(255) NOT NULL UNIQUE,
    workflow_code VARCHAR(100) NOT NULL UNIQUE,
    description LONGTEXT,
    process_type VARCHAR(50) NOT NULL,
    workflow_definition LONGTEXT,
    version INT DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    requires_approval BOOLEAN NOT NULL DEFAULT TRUE,
    max_approval_levels INT DEFAULT 1,
    timeout_days INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_workflow_code (workflow_code),
    INDEX idx_process_type (process_type),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Workflow Instances Table
CREATE TABLE IF NOT EXISTS workflow_instances (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    workflow_definition_id BIGINT NOT NULL,
    instance_number VARCHAR(100) NOT NULL UNIQUE,
    entity_type VARCHAR(100) NOT NULL,
    entity_id BIGINT NOT NULL,
    initiated_by BIGINT NOT NULL,
    initiated_at TIMESTAMP NOT NULL,
    current_step INT NOT NULL DEFAULT 0,
    current_approver_id BIGINT,
    status VARCHAR(50) DEFAULT 'IN_PROGRESS',
    approval_comments LONGTEXT,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    due_date TIMESTAMP,
    priority VARCHAR(50) DEFAULT 'MEDIUM',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_workflow_definition_id (workflow_definition_id),
    INDEX idx_entity_id (entity_id),
    INDEX idx_current_step (current_step),
    INDEX idx_status (status),
    INDEX idx_tenant_id (tenant_id),
    FOREIGN KEY (workflow_definition_id) REFERENCES workflow_definitions(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Report Templates Table
CREATE TABLE IF NOT EXISTS report_templates (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    template_name VARCHAR(255) NOT NULL UNIQUE,
    template_code VARCHAR(100) NOT NULL UNIQUE,
    description LONGTEXT,
    report_type VARCHAR(50) NOT NULL,
    report_category VARCHAR(100),
    template_definition LONGTEXT,
    display_format VARCHAR(50) DEFAULT 'TABLE',
    data_source_query LONGTEXT,
    refresh_frequency VARCHAR(50),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_scheduled BOOLEAN NOT NULL DEFAULT FALSE,
    scheduled_recipients LONGTEXT,
    owner_id BIGINT,
    version INT DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_template_code (template_code),
    INDEX idx_report_type (report_type),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Budgets Table
CREATE TABLE IF NOT EXISTS budgets (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    budget_name VARCHAR(255) NOT NULL,
    budget_code VARCHAR(100) NOT NULL UNIQUE,
    account_id BIGINT,
    department_id BIGINT,
    budget_period DATE NOT NULL,
    budget_amount DECIMAL(19,2) NOT NULL,
    actual_amount DECIMAL(19,2) DEFAULT 0.00,
    variance DECIMAL(19,2) DEFAULT 0.00,
    variance_percentage DECIMAL(5,2) DEFAULT 0.00,
    status VARCHAR(50) DEFAULT 'DRAFT',
    approved_by BIGINT,
    approval_date DATE,
    budget_notes TEXT,
    is_recurring BOOLEAN NOT NULL DEFAULT FALSE,
    alert_threshold DECIMAL(5,2),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by VARCHAR(255),
    updated_by VARCHAR(255),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMP NULL,
    tenant_id BIGINT,
    INDEX idx_account_id (account_id),
    INDEX idx_department_id (department_id),
    INDEX idx_budget_period (budget_period),
    INDEX idx_status (status),
    INDEX idx_tenant_id (tenant_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

